# Generated by Django 4.2.4 on 2023-12-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('companyname', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('emails', models.TextField(blank=True)),
                ('phones', models.TextField(blank=True)),
            ],
        ),
    ]
